name: PotatoPlugins
main: PotatoPlugin.MainClass
version: 1.0
commands:
    vote:
        usage:
        description:
    addurl:
        usage:
        description:
    plugins:
        usage:
        description:
    plugin:
        usage:
        description:
    pl:
        usage:
        description:
    ?:
         usage:
         description: