name: PotatoPlugins
main: PotatoPlugin.MainClass
version: 1.0
commands:
    vote:
        usage:
        description: Vote for the server
    addurl:
        usage:
        description: Add a url to /vote
    plugins:
        usage:
        description: No lookie!
    plugin:
        usage:
        description: No lookie!
    pl:
        usage:
        description: No lookie!
    ?:
        usage:
        description: No lookie!
    swearfilter:
        aliases: sf
        usage:
        description: SwearFilter add/del
    pshops:
        usage: /pshops
        description: Teleports you to the player shop world.
    pshopmenu:
        aliases: psm
        usage: /pshopmenu
        description: Opens the Player Shop Menu.
    sshop:
        usage: /sshop
        description: A command used to configuring sponsored shops.
    test:
        usage:
        description: Does absolutely nothing at all.
    bcshop:
        usage:
        description: Create PSM shop.
    ps:
        usage:
        description: Change Lore/Icon.
    configbroadcast:
        usage:
        description:
